import turtle
screen = turtle.Screen()
screen.setup(500, 500)
t = turtle.Turtle()

t.speed(2)
t.pensize(3)
t.penup()
t.goto(0, -150)
t.pendown()
t.begin_fill()
t.screen.bgcolor("gray")
t.color("yellow")
t.left(140)
t.forward(180)
t.circle(-90, 200)
t.left(120)
t.circle(-90, 200)
t.forward(180)
t.end_fill()
t.penup()
t.goto(-70, -50)
t.pendown()
t.color("red")
# t.write("N", align="left", font=("Arial", 90, "bold"))
t.penup()
t.goto(30, -50)
t.pendown()
t.hideturtle()

turtle.done()
